# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: helloAzureContainerRegistry
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          containerRegistry: helloazurecontainerregistry.azurecr.io
          tags: |
            '$(Build.BuildId)'
