apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "0 1 1 * *" # 每月执行一次，手动 Trigger
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-cronjob-pod
            image: "{{ $.Values.image.repository }}:{{ $.Chart.AppVersion }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
             {{- with .Values.env }}
            env:
              {{- toYaml . | nindent 12 }}
            {{- end}}
            volumeMounts:
            - name: "hello-cronjob-secrets-store"
              mountPath: "/mnt/hello-cronjob-secrets-store"
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: "hello-cronjob-secrets-store"
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "helloazurekv-secret-provider"