apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "0 1 1 * *" # 每月执行一次，手动 Trigger
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-cronjob-pod
            image: "{{ $.Values.image.repository }}:{{ $.Chart.AppVersion }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
             {{- with .Values.env }}
            env:
              {{- toYaml . | nindent 12 }}
            {{- end}}
            volumeMounts:
            {{- range $key, $value := .Values.keyvault.vaults }}
            - name: "{{ $.Values.fullnameOverride }}-{{ $key | lower }}"
              mountPath: "/mnt/{{ $key }}-secrets-store"
              readOnly: true
            {{- end }}
          restartPolicy: OnFailure
          volumes:
          {{- range $key, $value := .Values.keyvault.vaults }}
            - name: "{{ $.Values.fullnameOverride | lower }}-{{ $key | lower }}"
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "{{ $.Values.fullnameOverride | lower }}-{{ $key | lower }}"
          {{- end }}