apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "hello-secret-provider"
spec:
  provider: azure
  secretObjects:
    - secretName: hello-secrets
      type: Opaque
      labels:
        environment: default
      data:
        - objectName: oneSectetInKeyVault
          key: oneSectetInProvider
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: f8be5e9a-e60a-4b7b-abff-0459c4f6566e # helloAzureAks-agentpool's Client ID
    keyvaultName: "hellKeyvault"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: oneSectetInKeyVault
          objectType: secret
          objectVersion: ""
    tenantId: 6479215a-abae-4b35-b4e7-480d4e9c2799