apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "helloazurekv-secret-provider"
spec:
  provider: azure
  secretObjects:
    - secretName: my-secrets-from-keyvault
      type: Opaque
      labels:
        environment: default
      data:
        - objectName: myKeyVaultSecretName
          key: myScrectKeyName
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a7b4b9d7-bdb1-46ee-bdd1-d2d7430a3f03" # keyvault userAssignedIdentityID
    keyvaultName: helloAzureAkv
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: mykeyVaultSecretName
          objectType: secret
          objectVersion: ""
    tenantId: 6479215a-abae-4b35-b4e7-480d4e9c2799