apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "helloazurekv-secret-provider"
spec:
  provider: azure
  secretObjects:
    - secretName: my-secrets-from-keyvault
      type: Opaque
      labels:
        environment: default
      data:
        - objectName: myKeyVaultSecret
          key: mySecret
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a343bc7e-5aa4-4166-8ca6-868da5637b6a" #userAssignedIdentityID
    keyvaultName: helloAzureAkv
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: myKeyVaultSecret
          objectType: secret
          objectVersion: ""
    tenantId: 6479215a-abae-4b35-b4e7-480d4e9c2799