image:
  repository: helloazurecontainerregistry.azurecr.io/helloazure
  pullPolicy: Always
            
env:
  - name: "StorageAccountName"
    value: "My StorageAccountName Value"
  - name: "OneSectetInProvider"
    valueFrom:
      secretKeyRef:
        name: hello-secrets
        key: oneSectetInProvider 