image:
  repository: helloazurecontainerregistry.azurecr.io/helloazure
  pullPolicy: Always

env:
  - name: "StorageAccountName"
    value: "My StorageAccountName Value"
  - name: "MyKeyVaultValue"
    valueFrom:
      secretKeyRef:
        name: my-secrets-from-keyvault
        key: myScrectKeyName 